### ISSUE TITLE
Make 'permanent' particle vector channels

### ISSUE THREAD

**Issue by dimaleks** [cselab/YMeRo#15]
As of now, the extra particle vector channel are not persistent. They are communicated via MPI, but not preserved during the cell-list update. The goal is to make them truly stick:

- [x] Make CellList reorder data of the extra channels
- [x] Non-primary CellList should keep the reordered extra channels
- [ ] Views should be aware of the channels store within the non-primary CellList (e.g. for interactions with charge, etc.)
- [x] Permanent channels should be written and read to/from the restart files

**Comment by amlucas** [comment]
regarding views: seems very specific, leave it as it is for now
